Feature: Codec

  The codec is not an argument of the arithmetic.

  Every scenario below names the conformance ID it discharges, and a test
  whose name ends in that ID runs it. `cargo xtask check-model` fails if an
  ID here has no register row, or a register row has no scenario (CM-02).

  @CK-01 @build
  Scenario: Two codecs with equal decodes give equal output bytes
    Given the standing corpus
    When the suite exercises CK-01
    Then the claim holds byte for byte

  @CK-02 @build
  Scenario: Codec-invariance holds when both operands are coded
    Given the standing corpus
    When the suite exercises CK-02
    Then the claim holds byte for byte

  @CK-03 @build
  Scenario: The packed panels themselves are byte-equal across codecs that decode equally
    Given the standing corpus
    When the suite exercises CK-03
    Then the claim holds byte for byte

  @CK-04 @build
  Scenario: A transcoded stream equals the composite codec
    Given the standing corpus
    When the suite exercises CK-04
    Then the claim holds byte for byte

  @CK-05 @build
  Scenario: Two `CodedMatrix` values with different kappa labels and equal decodes give equal output bytes
    Given the standing corpus
    When the suite exercises CK-05
    Then the claim holds byte for byte

  @CK-06 @build
  Scenario: A run codec's returned counts sum to the declared row width on every row
    Given the standing corpus
    When the suite exercises CK-06
    Then the claim holds byte for byte

  @CK-08 @build
  Scenario: The canonical manifest is byte-stable, a short buffer reports the need, and a malformed digest is rejected
    Given the standing corpus
    When the suite exercises CK-08
    Then the claim holds byte for byte

  @CK-09 @build
  Scenario: `Enumerable`'s laws hold for every implementing codec
    Given the standing corpus
    When the suite exercises CK-09
    Then the claim holds byte for byte

  @CK-10 @build
  Scenario: An arena's codebook is canonical: distinct bit patterns, sorted and deduplicated
    Given the standing corpus
    When the suite exercises CK-10
    Then the claim holds byte for byte

  @CK-13 @build
  Scenario: Sign- and ternary-coded weights give the dense spelling's bytes, packed and tabulated
    Given the standing corpus
    When the suite exercises CK-13
    Then the claim holds byte for byte

  @CK-11 @build
  Scenario: The `Sign` tier decodes the `Packed<Grid<2>,8>` stream byte-identically and its index stream is the code stream
    Given the standing corpus
    When the suite exercises CK-11
    Then the claim holds byte for byte

  @CK-12 @build
  Scenario: The `Ternary` tier decodes the `Packed<Grid<4>,4>` stream byte-identically and its index stream is the code stream
    Given the standing corpus
    When the suite exercises CK-12
    Then the claim holds byte for byte

  @CK-14 @build
  Scenario: The arena tier at a u8 code width decodes the u16 spelling's stream byte-identically, and its codebook is borrowed, never owned
    Given the standing corpus
    When the suite exercises CK-14
    Then the claim holds byte for byte

  @CK-15 @build
  Scenario: The u8 spelling of a 256-entry tier stores half the bytes of the u16 spelling, decodes the same alphabet stream, and is byte-identical through the tabulated driver at every shape and offer, with the gather dispatched once per call between monomorphic u8 and u16 sequences
    Given the standing corpus
    When the suite exercises CK-15
    Then the claim holds byte for byte

  @CK-16 @build
  Scenario: The semiring laws hold at every instance, and idempotence holds precisely at the tropical instance and fails precisely at the ring
    Given the standing corpus
    When the suite exercises CK-16
    Then the claim holds byte for byte

  @CK-17 @build
  Scenario: The semiring zero is simultaneously the pad and the mask, so a masked shape and a zero-padded shape are byte-identical
    Given the standing corpus
    When the suite exercises CK-17
    Then the claim holds byte for byte

  @CK-18 @build
  Scenario: The complete signed i8 product alphabet is a lookup table generated by shift-add
    Given the standing corpus
    When the suite exercises CK-18
    Then every pair equals its independent shift-add product

  @CK-19 @build
  Scenario: Finite NAF is the canonical section of the dyadic quotient and its Atlas page address never wraps
    Given signed dyadic values and grades straddling context, scope, and word boundaries
    When the suite normalizes, evaluates, negates, encodes, and decodes CK-19
    Then the representative is unique, non-adjacent, evaluation-preserving, and addressed at the original grade

  @CK-20 @build
  Scenario: The scaled Atlas carrier decomposes exactly and its interaction block is load-bearing
    Given carriers in `3 Z^(3x8)` including the registered equal-marginal interaction witness
    When the suite applies all four canonical projectors for CK-20
    Then every coordinate is dyadic, the blocks reconstruct exactly, and the differing signed-digit values remain distinguishable

  @CK-21 @build
  Scenario: Every decoded float code has a lossless sixteen-byte packed form
    Given finite codes spanning both signs, the full mantissa and exponent domains, both non-finite sentinels, and nonreserved historical padding words
    When the suite packs and interprets each code for CK-21
    Then every decoded field is recovered, every kind is distinct, ordinary IEEE finite values remain inline, and nonreserved padding retains its prior kind
