// @generated by `cargo xtask check-model --write`.
// Source of truth: model/constants.toml, model/widths.toml.
// Do not edit. R10: every constant has exactly one source.

//! Constants generated from `model/*.toml`.
//!
//! Nothing here is a limit on the library. Every value is either a
//! property of a machine integer type, or a property of a caller's chosen
//! instantiation, or a narrow-register threshold, which is a question about
//! register width and not about what the library will accept (§5.1).

/// The schema tag every generated artifact carries.
pub const SPEC: &str = "uor-matmul/1";

/// The largest reduction depth any addressable machine can present.
///
/// Declared in `model/constants.toml`, not probed from the host, so the
/// accumulator type is the same on a 64-bit host, a 32-bit host, and wasm32.
/// A 32-bit host cannot reach this depth, which makes the width conservative
/// there and never wrong anywhere.
pub const MAX_K_BITS: u32 = 64;

/// Model-owned constants for the canonical Atlas embedding.
///
/// Crate-private: the representation phase does not change the public API.
#[allow(dead_code)]
pub(crate) mod atlas {
    /// Scoped copies of the carrier.
    pub(crate) const SCOPE: u32 = 4;
    /// Modality rows in one carrier.
    pub(crate) const MODALITY: u32 = 3;
    /// Ordered context sites in one scope.
    pub(crate) const CONTEXT: u32 = 8;
    /// Dimension of one modality-context carrier.
    pub(crate) const CARRIER_DIM: u64 = 24;
    /// Scoped class count.
    pub(crate) const CLASS_COUNT: u128 = 96;
    /// Ordered grade sites in one address word.
    pub(crate) const PAGE_SITES: u64 = 32;
    /// Independent context refinement signs.
    pub(crate) const REFINEMENT_BITS: u32 = 7;
    /// Context refinement leaves as `(coefficient, power_of_two)`.
    pub(crate) const REFINEMENT_LEAVES: (u128, u32) = (1, 7);
    /// Full scoped Atlas alphabet cardinality as `(coefficient, power_of_two)`.
    pub(crate) const ALPHABET: (u128, u32) = (96, 7);
    /// Input lattice scale cancelling the modality mean.
    pub(crate) const PROJECTOR_INPUT_SCALE: u32 = 3;
    /// Remaining implicit dyadic projector denominator.
    pub(crate) const PROJECTOR_DENOMINATOR: u32 = 8;
    /// Ranks of the four canonical projector blocks.
    pub(crate) const PROJECTOR_RANKS: [u128; 4] = [1, 2, 7, 14];
    /// Canonical signed-binary sites sufficient for `f32`.
    pub(crate) const F32_NAF_SITES: usize = 619;
    /// Atlas address words sufficient for `f32`.
    pub(crate) const F32_PAGES: usize = 20;
    /// Canonical signed-binary sites sufficient for `f64`.
    pub(crate) const F64_NAF_SITES: usize = 4261;
    /// Atlas address words sufficient for `f64`.
    pub(crate) const F64_PAGES: usize = 134;
}

/// Complete accumulator tail-word states (§3.3).
pub(crate) mod complete_state {
    /// First tail value reserved for a nonempty flag union.
    pub(crate) const BASE: i64 = i64::MIN;
    /// NaN bit in the former public Debug field order.
    pub(crate) const NAN_MASK: u8 = 1;
    /// Positive-infinity bit in the former public Debug field order.
    pub(crate) const POS_INF_MASK: u8 = 2;
    /// Negative-infinity bit in the former public Debug field order.
    pub(crate) const NEG_INF_MASK: u8 = 4;
    /// Singleton NaN sentinel.
    pub(crate) const NAN: i64 = BASE + NAN_MASK as i64 - 1;
    /// Singleton positive-infinity sentinel.
    pub(crate) const POS_INF: i64 = BASE + POS_INF_MASK as i64 - 1;
    /// Singleton negative-infinity sentinel.
    pub(crate) const NEG_INF: i64 = BASE + NEG_INF_MASK as i64 - 1;
    /// Number of nonempty flag unions reserved from the extension word.
    pub(crate) const COUNT: u32 = 7;
}

/// Worst-case accumulation width per element type (§3.2).
///
/// These are pins for `CM-01`. The library reads `acc_bits::<E>()`,
/// never these constants.
pub mod acc_width {
    /// `acc_bits::<i8>()` on a 64-bit host.
    pub const I8_BITS: u32 = 79;
    /// The accumulator `i8` resolves to.
    pub const I8_ACC_BITS: u32 = 128;
    /// `acc_bits::<i16>()` on a 64-bit host.
    pub const I16_BITS: u32 = 95;
    /// The accumulator `i16` resolves to.
    pub const I16_ACC_BITS: u32 = 128;
    /// `acc_bits::<i32>()` on a 64-bit host.
    pub const I32_BITS: u32 = 127;
    /// The accumulator `i32` resolves to.
    pub const I32_ACC_BITS: u32 = 128;
    /// `acc_bits::<i64>()` on a 64-bit host.
    pub const I64_BITS: u32 = 191;
    /// The accumulator `i64` resolves to.
    pub const I64_ACC_BITS: u32 = 192;
    /// `acc_bits::<Complex<i32>>()` on a 64-bit host.
    pub const COMPLEX_I32_BITS: u32 = 128;
    /// The accumulator `Complex<i32>` resolves to.
    pub const COMPLEX_I32_ACC_BITS: u32 = 128;
    /// `acc_bits::<Complex<i64>>()` on a 64-bit host.
    pub const COMPLEX_I64_BITS: u32 = 192;
    /// The accumulator `Complex<i64>` resolves to.
    pub const COMPLEX_I64_ACC_BITS: u32 = 192;
}

/// Complete accumulator widths for the float codecs (§3.3).
pub mod complete_width {
    /// Limbs spanning the whole `f32` product exponent range.
    pub const F32_LIMBS: usize = 10;
    /// Lowest representable product exponent for `f32`.
    pub const F32_MIN_PRODUCT_EXP: i32 = -298;
    /// Highest representable product exponent for `f32`.
    pub const F32_MAX_PRODUCT_EXP: i32 = 256;
    /// Limbs spanning the whole `f64` product exponent range.
    pub const F64_LIMBS: usize = 67;
    /// Lowest representable product exponent for `f64`.
    pub const F64_MIN_PRODUCT_EXP: i32 = -2148;
    /// Highest representable product exponent for `f64`.
    pub const F64_MAX_PRODUCT_EXP: i32 = 2048;
}

/// Narrow-register thresholds (§5.1, §7.3).
///
/// The `k` at which one instruction sequence stops being usable for a tile.
/// A tile past its threshold uses a wider register and computes the same
/// integer, so none of these is a limit on anything.
pub mod narrow {
    /// `i32::MAX`, the cap for a 32-bit lane.
    pub const CAP_I32: u128 = 2147483647;
    /// Worst-case magnitude of one step of: plain i32 tile, |a_i * w_i| <= 127 * 127.
    pub const I32_TILE_W8A8_PER_STEP: u128 = 16129;
    /// `floor(2147483647 / 16129)`.
    pub const I32_TILE_W8A8_K_MAX: u128 = 133144;
    /// Worst-case magnitude of one step of: offset to u8: |sum((a+128) * b)| <= 255 * 127.
    pub const VNNI_DPBUSD_W8A8_PER_STEP: u128 = 32385;
    /// `floor(2147483647 / 32385)`.
    pub const VNNI_DPBUSD_W8A8_K_MAX: u128 = 66311;
    /// Worst-case magnitude of one step of: offset compensation term: |128 * sum(b)| <= 128 * 127.
    pub const VNNI_DPBUSD_COMPENSATION_W8A8_PER_STEP: u128 = 16256;
    /// `floor(2147483647 / 16256)`.
    pub const VNNI_DPBUSD_COMPENSATION_W8A8_K_MAX: u128 = 132104;
    /// Worst-case magnitude of one step of: _mm256_madd_epi16 pair, |a0*w0 + a1*w1| <= 2 * 127 * 127.
    pub const AVX2_MADD_W8A8_PER_STEP: u128 = 32258;
    /// `floor(2147483647 / 32258)`.
    pub const AVX2_MADD_W8A8_K_MAX: u128 = 66572;
    /// Worst-case magnitude of one step of: vmull_s8 accumulated in i16, |a*w| <= 127 * 127.
    pub const NEON_VMULL_S16_W8A8_PER_STEP: u128 = 16129;
    /// `floor(32767 / 16129)`.
    pub const NEON_VMULL_S16_W8A8_K_MAX: u128 = 2;
    /// Worst-case magnitude of one step of: i64x2 SWAR broadcast: three biased fields at 21-bit spacing, |sum((a+128)*(b+128))| <= 255 * 255 a field.
    pub const WASM_SWAR_FIELD_W8A8_PER_STEP: u128 = 65025;
    /// `floor(2097151 / 65025)`.
    pub const WASM_SWAR_FIELD_W8A8_K_MAX: u128 = 32;
}

/// Canonical instantiations (§1.1).
///
/// W8A8 is the instantiation with the most instruction support and the most
/// external oracles. Nothing else privileges it, and a library user who
/// instantiates something else never sees any numeral from this module.
pub mod instantiation {
    /// The `W8A8` alphabet bound, over `i8`.
    pub const W8A8_BOUND: u128 = 127;
    /// The `W4A8` alphabet bound, over `i8`.
    pub const W4A8_BOUND: u128 = 7;
    /// The `W16A16` alphabet bound, over `i16`.
    pub const W16A16_BOUND: u128 = 32767;
}

/// Constants discovered by measurement.
///
/// Explicitly allowlisted out of R1: changing one cannot change any output
/// byte, only which traversal produces it, which is what `CD-01` asserts.
pub mod blocking {
    /// Rows of A per block.
    pub const MC: usize = 128;
    /// Depth per packed panel.
    pub const KC: usize = 256;
    /// Columns of B per block.
    pub const NC: usize = 1024;
    /// The machine's cache line, in bytes.
    pub const CACHE_LINE_BYTES: usize = 64;
    /// The first level of data cache, in bytes: what a tabulation table must fit.
    pub const L1_BYTES: usize = 32768;
    /// The cache a per-column read can afford: what a tabulation stack must fit.
    pub const L2_BYTES: usize = 524288;
    /// Products one instruction of a dense tile kernel issues.
    pub const KERNEL_PRODUCTS_PER_STEP: usize = 16;
    /// Rows of the output a dense tile kernel produces per call.
    pub const KERNEL_ROWS: usize = 6;
    /// The smallest base-case extent at which a level of the sub-cubic recursion pays on the i32-exact lane.
    pub const STRASSEN_MIN_EXTENT: usize = 384;
    /// The smallest base-case extent at which one level of the modular bilinear
    /// factorization pays on a modular lane. `usize::MAX` declares no finite
    /// automatic crossing for that row; the modular arm then declines while the
    /// explicit factorization remains total. `MEASUREMENT-LOG.md` owns the evidence.
    pub const STRASSEN_MODULAR_MIN_EXTENT: usize = 1024;
}

// R1: the W8A8 threshold, pinned. This is the one place in the shipped
// crates where the numeral appears, and it appears as a check on the
// derivation rather than as a definition.
const _: () = assert!(narrow::I32_TILE_W8A8_K_MAX == 2147483647 / 16129);
const _: () = assert!(narrow::I32_TILE_W8A8_K_MAX == 133144);
