// @generated by `cargo xtask check-model --write`.
// Source of truth: model/constants.toml, model/widths.toml.
// Do not edit. R10: every constant has exactly one source.

//! Constants generated from `model/*.toml`.
//!
//! Nothing here is a limit on the library. Every value is either a
//! property of a machine integer type, or a property of a caller's chosen
//! instantiation, or a narrow-register threshold, which is a question about
//! register width and not about what the library will accept (§5.1).

/// The schema tag every generated artifact carries.
pub const SPEC: &str = "uor-matmul/1";

/// The largest reduction depth any addressable machine can present.
///
/// Declared in `model/constants.toml`, not probed from the host, so the
/// accumulator type is the same on a 64-bit host, a 32-bit host, and wasm32.
/// A 32-bit host cannot reach this depth, which makes the width conservative
/// there and never wrong anywhere.
pub const MAX_K_BITS: u32 = 64;

/// Worst-case accumulation width per element type (§3.2).
///
/// These are pins for `CM-01`. The library reads `acc_bits::<E>()`,
/// never these constants.
pub mod acc_width {
    /// `acc_bits::<i8>()` on a 64-bit host.
    pub const I8_BITS: u32 = 79;
    /// The accumulator `i8` resolves to.
    pub const I8_ACC_BITS: u32 = 128;
    /// `acc_bits::<i16>()` on a 64-bit host.
    pub const I16_BITS: u32 = 95;
    /// The accumulator `i16` resolves to.
    pub const I16_ACC_BITS: u32 = 128;
    /// `acc_bits::<i32>()` on a 64-bit host.
    pub const I32_BITS: u32 = 127;
    /// The accumulator `i32` resolves to.
    pub const I32_ACC_BITS: u32 = 128;
    /// `acc_bits::<i64>()` on a 64-bit host.
    pub const I64_BITS: u32 = 191;
    /// The accumulator `i64` resolves to.
    pub const I64_ACC_BITS: u32 = 192;
    /// `acc_bits::<Complex<i32>>()` on a 64-bit host.
    pub const COMPLEX_I32_BITS: u32 = 128;
    /// The accumulator `Complex<i32>` resolves to.
    pub const COMPLEX_I32_ACC_BITS: u32 = 128;
    /// `acc_bits::<Complex<i64>>()` on a 64-bit host.
    pub const COMPLEX_I64_BITS: u32 = 192;
    /// The accumulator `Complex<i64>` resolves to.
    pub const COMPLEX_I64_ACC_BITS: u32 = 192;
}

/// Complete accumulator widths for the float codecs (§3.3).
pub mod complete_width {
    /// Limbs spanning the whole `f32` product exponent range.
    pub const F32_LIMBS: usize = 10;
    /// Lowest representable product exponent for `f32`.
    pub const F32_MIN_PRODUCT_EXP: i32 = -298;
    /// Highest representable product exponent for `f32`.
    pub const F32_MAX_PRODUCT_EXP: i32 = 256;
    /// Limbs spanning the whole `f64` product exponent range.
    pub const F64_LIMBS: usize = 67;
    /// Lowest representable product exponent for `f64`.
    pub const F64_MIN_PRODUCT_EXP: i32 = -2148;
    /// Highest representable product exponent for `f64`.
    pub const F64_MAX_PRODUCT_EXP: i32 = 2048;
}

/// Narrow-register thresholds (§5.1, §7.3).
///
/// The `k` at which one instruction sequence stops being usable for a tile.
/// A tile past its threshold uses a wider register and computes the same
/// integer, so none of these is a limit on anything.
pub mod narrow {
    /// `i32::MAX`, the cap for a 32-bit lane.
    pub const CAP_I32: u128 = 2147483647;
    /// Worst-case magnitude of one step of: plain i32 tile, |a_i * w_i| <= 127 * 127.
    pub const I32_TILE_W8A8_PER_STEP: u128 = 16129;
    /// `floor(2147483647 / 16129)`.
    pub const I32_TILE_W8A8_K_MAX: u128 = 133144;
    /// Worst-case magnitude of one step of: offset to u8: |sum((a+128) * b)| <= 255 * 127.
    pub const VNNI_DPBUSD_W8A8_PER_STEP: u128 = 32385;
    /// `floor(2147483647 / 32385)`.
    pub const VNNI_DPBUSD_W8A8_K_MAX: u128 = 66311;
    /// Worst-case magnitude of one step of: offset compensation term: |128 * sum(b)| <= 128 * 127.
    pub const VNNI_DPBUSD_COMPENSATION_W8A8_PER_STEP: u128 = 16256;
    /// `floor(2147483647 / 16256)`.
    pub const VNNI_DPBUSD_COMPENSATION_W8A8_K_MAX: u128 = 132104;
    /// Worst-case magnitude of one step of: _mm256_madd_epi16 pair, |a0*w0 + a1*w1| <= 2 * 127 * 127.
    pub const AVX2_MADD_W8A8_PER_STEP: u128 = 32258;
    /// `floor(2147483647 / 32258)`.
    pub const AVX2_MADD_W8A8_K_MAX: u128 = 66572;
    /// Worst-case magnitude of one step of: vmull_s8 accumulated in i16, |a*w| <= 127 * 127.
    pub const NEON_VMULL_S16_W8A8_PER_STEP: u128 = 16129;
    /// `floor(32767 / 16129)`.
    pub const NEON_VMULL_S16_W8A8_K_MAX: u128 = 2;
}

/// Canonical instantiations (§1.1).
///
/// W8A8 is the instantiation with the most instruction support and the most
/// external oracles. Nothing else privileges it, and a library user who
/// instantiates something else never sees any numeral from this module.
pub mod instantiation {
    /// The `W8A8` alphabet bound, over `i8`.
    pub const W8A8_BOUND: u128 = 127;
    /// The `W4A8` alphabet bound, over `i8`.
    pub const W4A8_BOUND: u128 = 7;
    /// The `W16A16` alphabet bound, over `i16`.
    pub const W16A16_BOUND: u128 = 32767;
}

/// Cache-shaped blocking parameters.
///
/// Explicitly allowlisted out of R1: changing one cannot change any output
/// byte, only which traversal produces it, which is what `CD-01` asserts.
pub mod blocking {
    /// Rows of A per block.
    pub const MC: usize = 128;
    /// Depth per packed panel.
    pub const KC: usize = 256;
    /// Columns of B per block.
    pub const NC: usize = 1024;
}

// R1: the W8A8 threshold, pinned. This is the one place in the shipped
// crates where the numeral appears, and it appears as a check on the
// derivation rather than as a definition.
const _: () = assert!(narrow::I32_TILE_W8A8_K_MAX == 2147483647 / 16129);
const _: () = assert!(narrow::I32_TILE_W8A8_K_MAX == 133144);
