// @generated by `cargo xtask check-model --write`.
// Source of truth: model/constants.toml [blocking] cache_line_bytes and [kernel_capacity], model/widths.toml [f32_q_carrier].
// Do not edit. R10: every constant has exactly one source.

/// Model-owned cache-line alignment for private kernel data.
pub(crate) const CACHE_LINE_BYTES: usize = 64;

/// Model-owned cache-line wrapper for private kernel data.
#[repr(align(64))]
pub(crate) struct CacheAligned<T>(pub(crate) T);

impl<T> core::ops::Deref for CacheAligned<T> {
    type Target = T;

    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

pub(crate) const MAX_TILE_LANES: usize = 128;
pub(crate) const MAX_ATLAS_SOURCE_SITES: usize = 24;

#[allow(dead_code)] // each private consumer reads only the dimensions its factorization needs
pub(crate) mod f32_q {
    pub(crate) const SIGNIFICAND_BITS: u32 = 24;
    pub(crate) const MIN_FACTOR_EXP: i32 = -149;
    pub(crate) const MAX_FACTOR_EXP: i32 = 104;
    pub(crate) const PRODUCT_MAGNITUDE_BITS: u32 = 48;
    pub(crate) const PRODUCT_BOUND: u64 = 281474943156225;
    pub(crate) const RELATIVE_GRADE_COUNT: u32 = 507;
    pub(crate) const SIGNED_FINITE_STATES: u32 = 1014;
    pub(crate) const STATE_COUNT: u32 = 1021;
    pub(crate) const STATE_BITS: u32 = 10;
    pub(crate) const TAG_PAYLOAD_BITS: u32 = 58;
    pub(crate) const TAG_INTERVAL: u64 = 288230376151711744;
    pub(crate) const TAG_BASE: u64 = 8935141660703064064;
    pub(crate) const COMPACT_CEILING: u64 = 8935141660703064063;
    pub(crate) const ZERO_SPAN_CAPACITY: u64 = 31744;
    pub(crate) const MAGNITUDE_RADIX: u64 = 281474976710656;
    pub(crate) const SPLIT_STATE: u32 = 1021;
}
