//! Generation of the Rust consts from the model (R10, `CM-01`).
//!
//! The generated file is committed, so that the shipped crates need no
//! `build.rs` and stay buildable on a target with no host toolchain.
//! `xtask check-model` regenerates it in memory and fails if the committed
//! bytes differ, which is what makes the model the single source rather than
//! merely the first source.

use core::fmt::Write as _;

use crate::{derive, Model};

/// A Rust identifier fragment for a model name.
///
/// `Complex<i32>` is a type in the model and a const-name fragment in the
/// generated file; the mapping is mechanical so that adding an element type
/// stays an entry in `model/constants.toml` and nothing else.
fn ident(name: &str) -> String {
    let mut out = String::new();
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_uppercase());
        } else if !out.ends_with('_') {
            out.push('_');
        }
    }
    out.trim_matches('_').to_string()
}

/// Where the generated consts live, relative to the repository root.
pub const GENERATED_PATH: &str = "crates/uor-matmul-core/src/generated.rs";

/// Render the generated consts for `model`.
pub fn render(model: &Model) -> String {
    let mut out = String::new();
    let w = &mut out;

    let _ = writeln!(w, "// @generated by `cargo xtask check-model --write`.");
    let _ = writeln!(
        w,
        "// Source of truth: model/constants.toml, model/widths.toml."
    );
    let _ = writeln!(
        w,
        "// Do not edit. R10: every constant has exactly one source."
    );
    let _ = writeln!(w);
    let _ = writeln!(w, "//! Constants generated from `model/*.toml`.");
    let _ = writeln!(w, "//!");
    let _ = writeln!(
        w,
        "//! Nothing here is a limit on the library. Every value is either a"
    );
    let _ = writeln!(
        w,
        "//! property of a machine integer type, or a property of a caller's chosen"
    );
    let _ = writeln!(
        w,
        "//! instantiation, or a narrow-register threshold, which is a question about"
    );
    let _ = writeln!(
        w,
        "//! register width and not about what the library will accept (\u{a7}5.1)."
    );
    let _ = writeln!(w);
    let _ = writeln!(w, "/// The schema tag every generated artifact carries.");
    let _ = writeln!(w, "pub const SPEC: &str = {:?};", model.constants.spec);
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "/// The largest reduction depth any addressable machine can present."
    );
    let _ = writeln!(w, "///");
    let _ = writeln!(
        w,
        "/// Declared in `model/constants.toml`, not probed from the host, so the"
    );
    let _ = writeln!(
        w,
        "/// accumulator type is the same on a 64-bit host, a 32-bit host, and wasm32."
    );
    let _ = writeln!(
        w,
        "/// A 32-bit host cannot reach this depth, which makes the width conservative"
    );
    let _ = writeln!(w, "/// there and never wrong anywhere.");
    let _ = writeln!(
        w,
        "pub const MAX_K_BITS: u32 = {};",
        model.constants.max_k_bits
    );

    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "/// Worst-case accumulation width per element type (\u{a7}3.2)."
    );
    let _ = writeln!(w, "///");
    let _ = writeln!(
        w,
        "/// These are pins for `CM-01`. The library reads `acc_bits::<E>()`,"
    );
    let _ = writeln!(w, "/// never these constants.");
    let _ = writeln!(w, "pub mod acc_width {{");
    for width in &model.widths.width {
        let up = ident(&width.element);
        let _ = writeln!(
            w,
            "    /// `acc_bits::<{}>()` on a 64-bit host.",
            width.element
        );
        let _ = writeln!(w, "    pub const {up}_BITS: u32 = {};", width.bits);
        let _ = writeln!(
            w,
            "    /// The accumulator `{}` resolves to.",
            width.element
        );
        let _ = writeln!(w, "    pub const {up}_ACC_BITS: u32 = {};", width.acc_bits);
    }
    let _ = writeln!(w, "}}");

    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "/// Complete accumulator widths for the float codecs (\u{a7}3.3)."
    );
    let _ = writeln!(w, "pub mod complete_width {{");
    for c in &model.widths.complete {
        let up = ident(&c.element);
        let _ = writeln!(
            w,
            "    /// Limbs spanning the whole `{}` product exponent range.",
            c.element
        );
        let _ = writeln!(w, "    pub const {up}_LIMBS: usize = {};", c.limbs);
        let _ = writeln!(
            w,
            "    /// Lowest representable product exponent for `{}`.",
            c.element
        );
        let _ = writeln!(
            w,
            "    pub const {up}_MIN_PRODUCT_EXP: i32 = {};",
            c.min_product_exp
        );
        let _ = writeln!(
            w,
            "    /// Highest representable product exponent for `{}`.",
            c.element
        );
        let _ = writeln!(
            w,
            "    pub const {up}_MAX_PRODUCT_EXP: i32 = {};",
            c.max_product_exp
        );
    }
    let _ = writeln!(w, "}}");

    let _ = writeln!(w);
    let _ = writeln!(w, "/// Narrow-register thresholds (\u{a7}5.1, \u{a7}7.3).");
    let _ = writeln!(w, "///");
    let _ = writeln!(
        w,
        "/// The `k` at which one instruction sequence stops being usable for a tile."
    );
    let _ = writeln!(
        w,
        "/// A tile past its threshold uses a wider register and computes the same"
    );
    let _ = writeln!(w, "/// integer, so none of these is a limit on anything.");
    let _ = writeln!(w, "pub mod narrow {{");
    let _ = writeln!(w, "    /// `i32::MAX`, the cap for a 32-bit lane.");
    let _ = writeln!(
        w,
        "    pub const CAP_I32: u128 = {};",
        model.constants.narrow.cap_i32
    );
    for t in &model.constants.narrow.threshold {
        let up = ident(&t.name);
        let cap = t.cap_override.unwrap_or(model.constants.narrow.cap_i32);
        let _ = writeln!(
            w,
            "    /// Worst-case magnitude of one step of: {}.",
            t.sequence
        );
        let _ = writeln!(w, "    pub const {up}_PER_STEP: u128 = {};", t.per_step);
        let _ = writeln!(w, "    /// `floor({cap} / {})`.", t.per_step);
        let _ = writeln!(w, "    pub const {up}_K_MAX: u128 = {};", t.k_max);
    }
    let _ = writeln!(w, "}}");

    let _ = writeln!(w);
    let _ = writeln!(w, "/// Canonical instantiations (\u{a7}1.1).");
    let _ = writeln!(w, "///");
    let _ = writeln!(
        w,
        "/// W8A8 is the instantiation with the most instruction support and the most"
    );
    let _ = writeln!(
        w,
        "/// external oracles. Nothing else privileges it, and a library user who"
    );
    let _ = writeln!(
        w,
        "/// instantiates something else never sees any numeral from this module."
    );
    let _ = writeln!(w, "pub mod instantiation {{");
    for i in &model.constants.instantiation {
        let up = ident(&i.name);
        let _ = writeln!(
            w,
            "    /// The `{}` alphabet bound, over `{}`.",
            i.name, i.element
        );
        let _ = writeln!(w, "    pub const {up}_BOUND: u128 = {};", i.bound);
    }
    let _ = writeln!(w, "}}");

    let _ = writeln!(w);
    let _ = writeln!(w, "/// Cache-shaped blocking parameters.");
    let _ = writeln!(w, "///");
    let _ = writeln!(
        w,
        "/// Explicitly allowlisted out of R1: changing one cannot change any output"
    );
    let _ = writeln!(
        w,
        "/// byte, only which traversal produces it, which is what `CD-01` asserts."
    );
    let _ = writeln!(w, "pub mod blocking {{");
    let _ = writeln!(w, "    /// Rows of A per block.");
    let _ = writeln!(
        w,
        "    pub const MC: usize = {};",
        model.constants.blocking.mc
    );
    let _ = writeln!(w, "    /// Depth per packed panel.");
    let _ = writeln!(
        w,
        "    pub const KC: usize = {};",
        model.constants.blocking.kc
    );
    let _ = writeln!(w, "    /// Columns of B per block.");
    let _ = writeln!(
        w,
        "    pub const NC: usize = {};",
        model.constants.blocking.nc
    );
    let _ = writeln!(w, "}}");

    // R1's pin. The plan permits `133144` to appear inside a `const _` assert
    // and nowhere else; this is that assert.
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "// R1: the W8A8 threshold, pinned. This is the one place in the shipped"
    );
    let _ = writeln!(
        w,
        "// crates where the numeral appears, and it appears as a check on the"
    );
    let _ = writeln!(w, "// derivation rather than as a definition.");
    let w8a8 = model
        .constants
        .narrow
        .threshold
        .iter()
        .find(|t| t.name == "i32_tile_w8a8");
    if let Some(t) = w8a8 {
        let cap = model.constants.narrow.cap_i32;
        let _ = writeln!(
            w,
            "const _: () = assert!(narrow::I32_TILE_W8A8_K_MAX == {} / {});",
            cap, t.per_step
        );
        let _ = writeln!(
            w,
            "const _: () = assert!(narrow::I32_TILE_W8A8_K_MAX == {});",
            derive::threshold(cap, t.per_step)
        );
    }

    out
}

/// Where the generated conformance index lives, relative to the repository root.
pub const CONFORMANCE_PATH: &str = "CONFORMANCE.md";

/// Render `CONFORMANCE.md` from the ID register.
///
/// The index is generated rather than written, so that an ID cannot exist in
/// the documentation without a register row, or in the register without
/// appearing in the documentation (R4, R10, `CM-02`).
pub fn render_conformance(model: &Model) -> String {
    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(
        w,
        "<!-- @generated by `cargo xtask check-model --write` from model/ids.toml. -->"
    );
    let _ = writeln!(
        w,
        "<!-- Do not edit. R10: the model is the single source. -->"
    );
    let _ = writeln!(w);
    let _ = writeln!(w, "# CONFORMANCE");
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "The conformance ID register. Every test name ends in its ID; a test whose"
    );
    let _ = writeln!(
        w,
        "ID is not listed here fails `cargo xtask check-model`, and so does an ID"
    );
    let _ = writeln!(w, "listed here with no scenario and no test (`CM-02`).");
    let _ = writeln!(w);
    let _ = writeln!(w, "The three honesty levels (R4):");
    let _ = writeln!(w);
    let _ = writeln!(w, "| Level | Meaning |");
    let _ = writeln!(w, "| --- | --- |");
    let _ = writeln!(
        w,
        "| `some-true` | A fact reproduced from an authority. **Not established here.** |"
    );
    let _ = writeln!(w, "| `build` | Constructed here and validated against its oracle. Evidence that the kernels realize the identity, not a proof of it. |");
    let _ = writeln!(w, "| `open` | Measured and reported. **Never asserted.** |");
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "There is no `CN-*` class. Negative testing presupposes inputs the library"
    );
    let _ = writeln!(
        w,
        "rejects, and by C6 there are none beyond non-existence of the requested"
    );
    let _ = writeln!(
        w,
        "object, which `CS-03` covers at view construction. The absence of that"
    );
    let _ = writeln!(
        w,
        "class is itself checked: `cargo xtask audit-limits` fails if any code path"
    );
    let _ = writeln!(w, "returns an error the model does not sanction.");
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "The **State** column is this repository's own record, not part of the"
    );
    let _ = writeln!(
        w,
        "specification. R15 says nothing is deferred; it is satisfied when no row"
    );
    let _ = writeln!(w, "reads `pending`. `STATUS.md` is the prose version.");

    let classes: &[(&str, &str)] = &[
        (
            "CS-",
            "Structural: public API shape, stride semantics, view construction",
        ),
        (
            "CT-",
            "Totality: the operation is infallible on everything it can represent",
        ),
        ("CD-", "Determinism: same inputs, same bytes"),
        (
            "CB-",
            "Backend parity: every backend equals the portable reference",
        ),
        ("CU-", "Purity: one method, no classical path, no fallback"),
        (
            "CK-",
            "Codec: tier equivalence, transcode, kappa addressing",
        ),
        ("CX-", "Cross-library agreement against an external library"),
        (
            "CA-",
            "Allocation and environment: zero heap, no_std, embedded and wasm",
        ),
        (
            "CP-",
            "Statistical / property-based, with sample size and seed recorded",
        ),
        (
            "CG-",
            "Scaling: fitted exponent, compared against the same fit for each oracle",
        ),
        (
            "CM-",
            "Model integrity: the model is the single source of every constant",
        ),
    ];

    for (prefix, title) in classes {
        let rows: Vec<_> = model
            .ids
            .id
            .iter()
            .filter(|r| r.id.starts_with(prefix))
            .collect();
        if rows.is_empty() {
            continue;
        }
        let _ = writeln!(w);
        let _ = writeln!(w, "## `{prefix}*` --- {title}");
        let _ = writeln!(w);
        let _ = writeln!(w, "| ID | Level | State | Statement |");
        let _ = writeln!(w, "| --- | --- | --- | --- |");
        for r in rows {
            let statement = r.statement.replace('\n', " ").replace('|', "\\|");
            let state = match r.state {
                crate::State::Implemented => "implemented",
                crate::State::Pending => "**pending**",
            };
            let _ = writeln!(
                w,
                "| `{}` | `{}` | {state} | {} |",
                r.id,
                r.level.as_str(),
                statement.trim()
            );
        }
    }

    let _ = writeln!(w);
    let _ = writeln!(w, "## Cited authorities");
    let _ = writeln!(w);
    let _ = writeln!(w, "Never re-derived, vendored, or gated on.");
    let _ = writeln!(w);
    let _ = writeln!(w, "| Authority | Citation | Evidence here |");
    let _ = writeln!(w, "| --- | --- | --- |");
    for a in &model.authorities.authority {
        let citation = a.citation.replace('\n', " ").replace('|', "\\|");
        let realized = if a.realized_by.is_empty() {
            "--".to_string()
        } else {
            a.realized_by
                .iter()
                .map(|i| format!("`{i}`"))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let _ = writeln!(w, "| `{}` | {} | {realized} |", a.id, citation.trim());
    }

    let _ = writeln!(w);
    let _ = writeln!(w, "## Claims that are not conformance IDs");
    let _ = writeln!(w);
    let _ = writeln!(w, "| ID | Level | Claim |");
    let _ = writeln!(w, "| --- | --- | --- |");
    for c in &model.ledger.claim {
        let statement = c.statement.replace('\n', " ").replace('|', "\\|");
        let _ = writeln!(
            w,
            "| `{}` | `{}` | {} |",
            c.id,
            c.level.as_str(),
            statement.trim()
        );
    }

    out
}
