//! Generation of the Rust consts from the model (R10, `CM-01`).
//!
//! The generated file is committed, so that the shipped crates need no
//! `build.rs` and stay buildable on a target with no host toolchain.
//! `xtask check-model` regenerates it in memory and fails if the committed
//! bytes differ, which is what makes the model the single source rather than
//! merely the first source.

use core::fmt::Write as _;

use crate::{derive, Model};

/// A Rust identifier fragment for a model name.
///
/// `Complex<i32>` is a type in the model and a const-name fragment in the
/// generated file; the mapping is mechanical so that adding an element type
/// stays an entry in `model/constants.toml` and nothing else.
fn ident(name: &str) -> String {
    let mut out = String::new();
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_uppercase());
        } else if !out.ends_with('_') {
            out.push('_');
        }
    }
    out.trim_matches('_').to_string()
}

/// Where the generated consts live, relative to the repository root.
pub const GENERATED_PATH: &str = "crates/uor-matmul-core/src/generated.rs";

/// Where the generated private kernel-family capacity lives.
pub const KERNEL_CAPACITY_PATH: &str = "crates/uor-matmul-kernels/src/generated_capacity.rs";

/// Where the generated exhaustive Atlas const-frame dispatcher lives.
pub const ATLAS_DISPATCH_PATH: &str = "crates/uor-matmul-gemm/src/generated_atlas_dispatch.rs";

/// Render the private binary32 q-carrier geometry for one consuming crate.
///
/// Both consumers receive the same generated bytes in their existing private
/// artifacts. Sharing a public core symbol would expand the locked API, while
/// hand-restating either copy would give the constants a second source.
fn render_f32_q(model: &Model) -> String {
    let q = &model.widths.f32_q_carrier;
    let magnitude_radix = derive::power_of_two(q.product_magnitude_bits)
        .and_then(|value| u64::try_from(value).ok())
        .expect("the checked q magnitude radix fits u64");
    format!(
        "#[allow(dead_code)] // each private consumer reads only the dimensions its factorization needs\n\
         pub(crate) mod f32_q {{\n\
         \x20   pub(crate) const SIGNIFICAND_BITS: u32 = {};\n\
         \x20   pub(crate) const MIN_FACTOR_EXP: i32 = {};\n\
         \x20   pub(crate) const MAX_FACTOR_EXP: i32 = {};\n\
         \x20   pub(crate) const PRODUCT_MAGNITUDE_BITS: u32 = {};\n\
         \x20   pub(crate) const PRODUCT_BOUND: u64 = {};\n\
         \x20   pub(crate) const RELATIVE_GRADE_COUNT: u32 = {};\n\
         \x20   pub(crate) const SIGNED_FINITE_STATES: u32 = {};\n\
         \x20   pub(crate) const STATE_COUNT: u32 = {};\n\
         \x20   pub(crate) const STATE_BITS: u32 = {};\n\
         \x20   pub(crate) const TAG_PAYLOAD_BITS: u32 = {};\n\
         \x20   pub(crate) const TAG_INTERVAL: u64 = {};\n\
         \x20   pub(crate) const TAG_BASE: u64 = {};\n\
         \x20   pub(crate) const COMPACT_CEILING: u64 = {};\n\
         \x20   pub(crate) const ZERO_SPAN_CAPACITY: u64 = {};\n\
         \x20   pub(crate) const MAGNITUDE_RADIX: u64 = {magnitude_radix};\n\
         \x20   pub(crate) const SPLIT_STATE: u32 = {};\n\
         }}\n",
        q.significand_bits,
        q.min_factor_exp,
        q.max_factor_exp,
        q.product_magnitude_bits,
        q.product_bound,
        q.relative_grade_count,
        q.signed_finite_states,
        q.state_count,
        q.state_bits,
        q.tag_payload_bits,
        q.tag_interval,
        q.tag_base,
        q.compact_ceiling,
        q.zero_span_capacity,
        q.state_count,
    )
}

/// Render the private kernel capacities consumed by the stable public alias
/// and the family declaration assertions.
pub fn render_kernel_capacity(model: &Model) -> String {
    format!(
        "// @generated by `cargo xtask check-model --write`.\n\
         // Source of truth: model/constants.toml [blocking] cache_line_bytes and [kernel_capacity], model/widths.toml [f32_q_carrier].\n\
         // Do not edit. R10: every constant has exactly one source.\n\n\
         /// Model-owned cache-line alignment for private kernel data.\n\
         pub(crate) const CACHE_LINE_BYTES: usize = {};\n\n\
         /// Model-owned cache-line wrapper for private kernel data.\n\
         #[repr(align({}))]\n\
         pub(crate) struct CacheAligned<T>(pub(crate) T);\n\n\
         impl<T> core::ops::Deref for CacheAligned<T> {{\n\
         \x20\x20\x20\x20type Target = T;\n\n\
         \x20\x20\x20\x20#[inline(always)]\n\
         \x20\x20\x20\x20fn deref(&self) -> &Self::Target {{\n\
         \x20\x20\x20\x20\x20\x20\x20\x20&self.0\n\
         \x20\x20\x20\x20}}\n\
         }}\n\n\
         pub(crate) const MAX_TILE_LANES: usize = {};\n\
         pub(crate) const MAX_ATLAS_SOURCE_SITES: usize = {};\n\n\
         {}",
        model.constants.blocking.cache_line_bytes,
        model.constants.blocking.cache_line_bytes,
        model.constants.kernel_capacity.max_tile_lanes,
        model.constants.kernel_capacity.max_source_sites,
        render_f32_q(model),
    )
}

/// Render every admissible const-generic Atlas frame exactly once.
///
/// Rust cannot instantiate an array length from a runtime value.  Emitting the
/// finite declaration interval is therefore the zero-overhead bridge from the
/// selected physical tile to its exact stack frame.  Generation makes the
/// interval a consequence of the model-owned family maximum rather than a
/// second hand-maintained limit.
pub fn render_atlas_dispatch(model: &Model) -> String {
    let maximum = model.constants.kernel_capacity.max_tile_lanes;
    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(w, "// @generated by `cargo xtask check-model --write`.");
    let _ = writeln!(
        w,
        "// Source of truth: model/constants.toml [kernel_capacity], [column_hash]; model/widths.toml [f32_q_carrier]."
    );
    let _ = writeln!(w, "// Do not edit. R10: every arm has exactly one source.");
    let _ = writeln!(w);
    let _ = writeln!(w, "{}", render_f32_q(model));
    let _ = writeln!(
        w,
        "pub(crate) const COLUMN_HASH_PREFIX: usize = {};",
        model.constants.column_hash.prefix
    );
    let _ = writeln!(
        w,
        "const MAX_ATLAS_SOURCE_SITES: usize = {};",
        model.constants.kernel_capacity.max_source_sites
    );
    let _ = writeln!(w, "macro_rules! dispatch_atlas_cell_capacity {{");
    let _ = writeln!(w, "    ($capacity:expr, $execute:ident) => {{");
    let _ = writeln!(w, "        match $capacity {{");
    for capacity in 1..maximum {
        let _ = writeln!(w, "            {capacity} => $execute!({capacity}),");
    }
    let _ = writeln!(
        w,
        "            MAX_TILE_LANES => $execute!(MAX_TILE_LANES),"
    );
    let _ = writeln!(
        w,
        "            _ => unreachable!(\"a physical kernel tile cannot exceed MAX_TILE_LANES\"),"
    );
    let _ = writeln!(w, "        }}");
    let _ = writeln!(w, "    }};");
    let _ = writeln!(w, "}}");
    out
}

/// Render the generated consts for `model`.
pub fn render(model: &Model) -> String {
    let mut out = String::new();
    let w = &mut out;

    let _ = writeln!(w, "// @generated by `cargo xtask check-model --write`.");
    let _ = writeln!(
        w,
        "// Source of truth: model/constants.toml, model/widths.toml."
    );
    let _ = writeln!(
        w,
        "// Do not edit. R10: every constant has exactly one source."
    );
    let _ = writeln!(w);
    let _ = writeln!(w, "//! Constants generated from `model/*.toml`.");
    let _ = writeln!(w, "//!");
    let _ = writeln!(
        w,
        "//! Nothing here is a limit on the library. Every value is either a"
    );
    let _ = writeln!(
        w,
        "//! property of a machine integer type, or a property of a caller's chosen"
    );
    let _ = writeln!(
        w,
        "//! instantiation, or a narrow-register threshold, which is a question about"
    );
    let _ = writeln!(
        w,
        "//! register width and not about what the library will accept (\u{a7}5.1)."
    );
    let _ = writeln!(w);
    let _ = writeln!(w, "/// The schema tag every generated artifact carries.");
    let _ = writeln!(w, "pub const SPEC: &str = {:?};", model.constants.spec);
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "/// The largest reduction depth any addressable machine can present."
    );
    let _ = writeln!(w, "///");
    let _ = writeln!(
        w,
        "/// Declared in `model/constants.toml`, not probed from the host, so the"
    );
    let _ = writeln!(
        w,
        "/// accumulator type is the same on a 64-bit host, a 32-bit host, and wasm32."
    );
    let _ = writeln!(
        w,
        "/// A 32-bit host cannot reach this depth, which makes the width conservative"
    );
    let _ = writeln!(w, "/// there and never wrong anywhere.");
    let _ = writeln!(
        w,
        "pub const MAX_K_BITS: u32 = {};",
        model.constants.max_k_bits
    );

    let atlas = &model.constants.atlas;
    let carrier = derive::atlas_carrier_dim(atlas.modality, atlas.context);
    let classes = derive::atlas_class_count(atlas.scope, atlas.modality, atlas.context);
    let page_sites = derive::atlas_page_sites(atlas.scope, atlas.context);
    let refinement_bits = derive::atlas_refinement_bits(atlas.context);
    let refinement_leaves = derive::atlas_refinement_leaves(atlas.context);
    let alphabet = derive::atlas_alphabet(atlas.scope, atlas.modality, atlas.context);
    let ranks = derive::atlas_projector_ranks(atlas.modality, atlas.context);
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "/// Model-owned constants for the canonical Atlas embedding."
    );
    let _ = writeln!(w, "///");
    let _ = writeln!(
        w,
        "/// Crate-private: the representation phase does not change the public API."
    );
    let _ = writeln!(w, "#[allow(dead_code)]");
    let _ = writeln!(w, "pub(crate) mod atlas {{");
    let _ = writeln!(w, "    /// Scoped copies of the carrier.");
    let _ = writeln!(w, "    pub(crate) const SCOPE: u32 = {};", atlas.scope);
    let _ = writeln!(w, "    /// Modality rows in one carrier.");
    let _ = writeln!(
        w,
        "    pub(crate) const MODALITY: u32 = {};",
        atlas.modality
    );
    let _ = writeln!(w, "    /// Ordered context sites in one scope.");
    let _ = writeln!(w, "    pub(crate) const CONTEXT: u32 = {};", atlas.context);
    let _ = writeln!(w, "    /// Dimension of one modality-context carrier.");
    let _ = writeln!(w, "    pub(crate) const CARRIER_DIM: u64 = {carrier};");
    let _ = writeln!(w, "    /// Scoped class count.");
    let _ = writeln!(w, "    pub(crate) const CLASS_COUNT: u128 = {classes};");
    let _ = writeln!(w, "    /// Ordered grade sites in one address word.");
    let _ = writeln!(w, "    pub(crate) const PAGE_SITES: u64 = {page_sites};");
    let _ = writeln!(w, "    /// Independent context refinement signs.");
    let _ = writeln!(
        w,
        "    pub(crate) const REFINEMENT_BITS: u32 = {refinement_bits};"
    );
    let _ = writeln!(
        w,
        "    /// Context refinement leaves as `(coefficient, power_of_two)`."
    );
    let _ = writeln!(
        w,
        "    pub(crate) const REFINEMENT_LEAVES: (u128, u32) = ({}, {});",
        refinement_leaves.coefficient(),
        refinement_leaves.power()
    );
    let _ = writeln!(
        w,
        "    /// Full scoped Atlas alphabet cardinality as `(coefficient, power_of_two)`."
    );
    let _ = writeln!(
        w,
        "    pub(crate) const ALPHABET: (u128, u32) = ({}, {});",
        alphabet.coefficient(),
        alphabet.power()
    );
    let _ = writeln!(
        w,
        "    /// Input lattice scale cancelling the modality mean."
    );
    let _ = writeln!(
        w,
        "    pub(crate) const PROJECTOR_INPUT_SCALE: u32 = {};",
        atlas.modality
    );
    let _ = writeln!(
        w,
        "    /// Remaining implicit dyadic projector denominator."
    );
    let _ = writeln!(
        w,
        "    pub(crate) const PROJECTOR_DENOMINATOR: u32 = {};",
        atlas.context
    );
    let _ = writeln!(w, "    /// Ranks of the four canonical projector blocks.");
    let _ = writeln!(
        w,
        "    pub(crate) const PROJECTOR_RANKS: [u128; 4] = {:?};",
        ranks
    );
    for c in &model.widths.complete {
        let up = ident(&c.element);
        let _ = writeln!(
            w,
            "    /// Canonical signed-binary sites sufficient for `{}`.",
            c.element
        );
        let _ = writeln!(
            w,
            "    pub(crate) const {up}_NAF_SITES: usize = {};",
            c.naf_sites
        );
        let _ = writeln!(
            w,
            "    /// Atlas address words sufficient for `{}`.",
            c.element
        );
        let _ = writeln!(
            w,
            "    pub(crate) const {up}_PAGES: usize = {};",
            c.atlas_pages
        );
    }
    let _ = writeln!(w, "}}");

    let _ = writeln!(w);
    let _ = writeln!(w, "/// Complete accumulator tail-word states (§3.3).");
    let _ = writeln!(w, "pub(crate) mod complete_state {{");
    let _ = writeln!(
        w,
        "    /// First tail value reserved for a nonempty flag union."
    );
    let _ = writeln!(w, "    pub(crate) const BASE: i64 = i64::MIN;");
    let _ = writeln!(w, "    /// NaN bit in the former public Debug field order.");
    let _ = writeln!(w, "    pub(crate) const NAN_MASK: u8 = 1;");
    let _ = writeln!(
        w,
        "    /// Positive-infinity bit in the former public Debug field order."
    );
    let _ = writeln!(w, "    pub(crate) const POS_INF_MASK: u8 = 2;");
    let _ = writeln!(
        w,
        "    /// Negative-infinity bit in the former public Debug field order."
    );
    let _ = writeln!(w, "    pub(crate) const NEG_INF_MASK: u8 = 4;");
    let _ = writeln!(w, "    /// Singleton NaN sentinel.");
    let _ = writeln!(
        w,
        "    pub(crate) const NAN: i64 = BASE + NAN_MASK as i64 - 1;"
    );
    let _ = writeln!(w, "    /// Singleton positive-infinity sentinel.");
    let _ = writeln!(
        w,
        "    pub(crate) const POS_INF: i64 = BASE + POS_INF_MASK as i64 - 1;"
    );
    let _ = writeln!(w, "    /// Singleton negative-infinity sentinel.");
    let _ = writeln!(
        w,
        "    pub(crate) const NEG_INF: i64 = BASE + NEG_INF_MASK as i64 - 1;"
    );
    let _ = writeln!(
        w,
        "    /// Number of nonempty flag unions reserved from the extension word."
    );
    let _ = writeln!(
        w,
        "    pub(crate) const COUNT: u32 = {};",
        model.widths.complete_state.nonfinite_states
    );
    let _ = writeln!(w, "}}");

    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "/// Worst-case accumulation width per element type (\u{a7}3.2)."
    );
    let _ = writeln!(w, "///");
    let _ = writeln!(
        w,
        "/// These are pins for `CM-01`. The library reads `acc_bits::<E>()`,"
    );
    let _ = writeln!(w, "/// never these constants.");
    let _ = writeln!(w, "pub mod acc_width {{");
    for width in &model.widths.width {
        let up = ident(&width.element);
        let _ = writeln!(
            w,
            "    /// `acc_bits::<{}>()` on a 64-bit host.",
            width.element
        );
        let _ = writeln!(w, "    pub const {up}_BITS: u32 = {};", width.bits);
        let _ = writeln!(
            w,
            "    /// The accumulator `{}` resolves to.",
            width.element
        );
        let _ = writeln!(w, "    pub const {up}_ACC_BITS: u32 = {};", width.acc_bits);
    }
    let _ = writeln!(w, "}}");

    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "/// Complete accumulator widths for the float codecs (\u{a7}3.3)."
    );
    let _ = writeln!(w, "pub mod complete_width {{");
    for c in &model.widths.complete {
        let up = ident(&c.element);
        let _ = writeln!(
            w,
            "    /// Limbs spanning the whole `{}` product exponent range.",
            c.element
        );
        let _ = writeln!(w, "    pub const {up}_LIMBS: usize = {};", c.limbs);
        let _ = writeln!(
            w,
            "    /// Lowest representable product exponent for `{}`.",
            c.element
        );
        let _ = writeln!(
            w,
            "    pub const {up}_MIN_PRODUCT_EXP: i32 = {};",
            c.min_product_exp
        );
        let _ = writeln!(
            w,
            "    /// Highest representable product exponent for `{}`.",
            c.element
        );
        let _ = writeln!(
            w,
            "    pub const {up}_MAX_PRODUCT_EXP: i32 = {};",
            c.max_product_exp
        );
    }
    let _ = writeln!(w, "}}");

    let _ = writeln!(w);
    let _ = writeln!(w, "/// Narrow-register thresholds (\u{a7}5.1, \u{a7}7.3).");
    let _ = writeln!(w, "///");
    let _ = writeln!(
        w,
        "/// The `k` at which one instruction sequence stops being usable for a tile."
    );
    let _ = writeln!(
        w,
        "/// A tile past its threshold uses a wider register and computes the same"
    );
    let _ = writeln!(w, "/// integer, so none of these is a limit on anything.");
    let _ = writeln!(w, "pub mod narrow {{");
    let _ = writeln!(w, "    /// `i32::MAX`, the cap for a 32-bit lane.");
    let _ = writeln!(
        w,
        "    pub const CAP_I32: u128 = {};",
        model.constants.narrow.cap_i32
    );
    for t in &model.constants.narrow.threshold {
        let up = ident(&t.name);
        let cap = t.cap_override.unwrap_or(model.constants.narrow.cap_i32);
        let _ = writeln!(
            w,
            "    /// Worst-case magnitude of one step of: {}.",
            t.sequence
        );
        let _ = writeln!(w, "    pub const {up}_PER_STEP: u128 = {};", t.per_step);
        let _ = writeln!(w, "    /// `floor({cap} / {})`.", t.per_step);
        let _ = writeln!(w, "    pub const {up}_K_MAX: u128 = {};", t.k_max);
    }
    let _ = writeln!(w, "}}");

    let _ = writeln!(w);
    let _ = writeln!(w, "/// Canonical instantiations (\u{a7}1.1).");
    let _ = writeln!(w, "///");
    let _ = writeln!(
        w,
        "/// W8A8 is the instantiation with the most instruction support and the most"
    );
    let _ = writeln!(
        w,
        "/// external oracles. Nothing else privileges it, and a library user who"
    );
    let _ = writeln!(
        w,
        "/// instantiates something else never sees any numeral from this module."
    );
    let _ = writeln!(w, "pub mod instantiation {{");
    for i in &model.constants.instantiation {
        let up = ident(&i.name);
        let _ = writeln!(
            w,
            "    /// The `{}` alphabet bound, over `{}`.",
            i.name, i.element
        );
        let _ = writeln!(w, "    pub const {up}_BOUND: u128 = {};", i.bound);
    }
    let _ = writeln!(w, "}}");

    let _ = writeln!(w);
    let _ = writeln!(w, "/// Constants discovered by measurement.");
    let _ = writeln!(w, "///");
    let _ = writeln!(
        w,
        "/// Explicitly allowlisted out of R1: changing one cannot change any output"
    );
    let _ = writeln!(
        w,
        "/// byte, only which traversal produces it, which is what `CD-01` asserts."
    );
    let _ = writeln!(w, "pub mod blocking {{");
    let _ = writeln!(w, "    /// Rows of A per block.");
    let _ = writeln!(
        w,
        "    pub const MC: usize = {};",
        model.constants.blocking.mc
    );
    let _ = writeln!(w, "    /// Depth per packed panel.");
    let _ = writeln!(
        w,
        "    pub const KC: usize = {};",
        model.constants.blocking.kc
    );
    let _ = writeln!(w, "    /// Columns of B per block.");
    let _ = writeln!(
        w,
        "    pub const NC: usize = {};",
        model.constants.blocking.nc
    );
    let _ = writeln!(w, "    /// The machine's cache line, in bytes.");
    let _ = writeln!(
        w,
        "    pub const CACHE_LINE_BYTES: usize = {};",
        model.constants.blocking.cache_line_bytes
    );
    let _ = writeln!(
        w,
        "    /// The first level of data cache, in bytes: what a tabulation table \
         must fit."
    );
    let _ = writeln!(
        w,
        "    pub const L1_BYTES: usize = {};",
        model.constants.blocking.l1_bytes
    );
    let _ = writeln!(
        w,
        "    /// The cache a per-column read can afford: what a tabulation stack \
         must fit."
    );
    let _ = writeln!(
        w,
        "    pub const L2_BYTES: usize = {};",
        model.constants.blocking.l2_bytes
    );
    let _ = writeln!(
        w,
        "    /// Products one instruction of a dense tile kernel issues."
    );
    let _ = writeln!(
        w,
        "    pub const KERNEL_PRODUCTS_PER_STEP: usize = {};",
        model.constants.blocking.kernel_products_per_step
    );
    let _ = writeln!(
        w,
        "    /// Rows of the output a dense tile kernel produces per call."
    );
    let _ = writeln!(
        w,
        "    pub const KERNEL_ROWS: usize = {};",
        model.constants.blocking.kernel_rows
    );
    let _ = writeln!(
        w,
        "    /// The smallest base-case extent at which a level of the sub-cubic recursion pays on the i32-exact lane."
    );
    let _ = writeln!(
        w,
        "    pub const STRASSEN_MIN_EXTENT: usize = {};",
        model.constants.blocking.strassen_min_extent
    );
    let _ = writeln!(
        w,
        "    /// The smallest base-case extent at which one level of the modular bilinear"
    );
    let _ = writeln!(
        w,
        "    /// factorization pays on a modular lane. `usize::MAX` declares no finite"
    );
    let _ = writeln!(
        w,
        "    /// automatic crossing for that row; the modular arm then declines while the"
    );
    let _ = writeln!(
        w,
        "    /// explicit factorization remains total. `MEASUREMENT-LOG.md` owns the evidence."
    );
    let modular = model.constants.blocking.strassen_modular_min_extent;
    if modular > u32::MAX as usize {
        // The explicit no-finite-auto-crossing declaration: a value past every
        // target's addressable extent, spelled so a 32-bit target declines too.
        let _ = writeln!(
            w,
            "    pub const STRASSEN_MODULAR_MIN_EXTENT: usize = usize::MAX;"
        );
    } else {
        let _ = writeln!(
            w,
            "    pub const STRASSEN_MODULAR_MIN_EXTENT: usize = {modular};"
        );
    }
    let _ = writeln!(w, "}}");

    // R1's pin. The plan permits `133144` to appear inside a `const _` assert
    // and nowhere else; this is that assert.
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "// R1: the W8A8 threshold, pinned. This is the one place in the shipped"
    );
    let _ = writeln!(
        w,
        "// crates where the numeral appears, and it appears as a check on the"
    );
    let _ = writeln!(w, "// derivation rather than as a definition.");
    let w8a8 = model
        .constants
        .narrow
        .threshold
        .iter()
        .find(|t| t.name == "i32_tile_w8a8");
    if let Some(t) = w8a8 {
        let cap = model.constants.narrow.cap_i32;
        let _ = writeln!(
            w,
            "const _: () = assert!(narrow::I32_TILE_W8A8_K_MAX == {} / {});",
            cap, t.per_step
        );
        let _ = writeln!(
            w,
            "const _: () = assert!(narrow::I32_TILE_W8A8_K_MAX == {});",
            derive::threshold(cap, t.per_step)
        );
    }

    out
}

/// Where the generated conformance index lives, relative to the repository root.
pub const CONFORMANCE_PATH: &str = "CONFORMANCE.md";

/// The conformance classes `CONFORMANCE.md` renders, in the order it renders
/// them.
///
/// Public because the register is checked against it. Grouping by class means
/// a class the generator does not know renders nothing at all, and that
/// omission is invisible to `check-model`'s byte comparison: the rendered
/// bytes and the committed bytes agree, because both leave the row out. So the
/// completeness of this list is enforced where it can be seen ---
/// [`crate::Model::check`] refuses a register row no class here covers --- and
/// adding a class is one edit to this array rather than a row that quietly
/// never appears.
pub const CLASSES: &[(&str, &str)] = &[
    (
        "CS-",
        "Structural: public API shape, stride semantics, view construction",
    ),
    (
        "CT-",
        "Totality: the operation is infallible on everything it can represent",
    ),
    ("CD-", "Determinism: same inputs, same bytes"),
    (
        "CB-",
        "Backend parity: every backend equals the portable reference",
    ),
    (
        "CU-",
        "Purity: one answer, many factorizations; no classical path, no fallback",
    ),
    (
        "CK-",
        "Codec: tier equivalence, transcode, kappa addressing",
    ),
    ("CX-", "Cross-library agreement against an external library"),
    (
        "CA-",
        "Allocation and environment: zero heap, no_std, embedded and wasm",
    ),
    (
        "CP-",
        "Statistical / property-based, with sample size and seed recorded",
    ),
    (
        "CG-",
        "Scaling: fitted exponent, compared against the same fit for each oracle",
    ),
    (
        "CM-",
        "Model integrity: the model is the single source of every constant",
    ),
];

/// One markdown table cell: newlines folded to spaces, pipes escaped, edges
/// trimmed.
///
/// The model authors its statements as TOML block strings so they stay
/// readable where they are written; a table row is one line. The fold belongs
/// here rather than as a constraint on how the model is spelled.
fn cell(text: &str) -> String {
    text.replace('\n', " ")
        .replace('|', "\\|")
        .trim()
        .to_string()
}

/// Render `CONFORMANCE.md` from the ID register.
///
/// The index is generated rather than written, so that an ID cannot exist in
/// the documentation without a register row, or in the register without
/// appearing in the documentation (R4, R10, `CM-02`).
pub fn render_conformance(model: &Model) -> String {
    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(
        w,
        "<!-- @generated by `cargo xtask check-model --write` from model/ids.toml. -->"
    );
    let _ = writeln!(
        w,
        "<!-- Do not edit. R10: the model is the single source. -->"
    );
    let _ = writeln!(w);
    let _ = writeln!(w, "# CONFORMANCE");
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "The conformance ID register. Every test name ends in its ID; a test whose"
    );
    let _ = writeln!(
        w,
        "ID is not listed here fails `cargo xtask check-model`, and so does an ID"
    );
    let _ = writeln!(w, "listed here with no scenario and no test (`CM-02`).");
    let _ = writeln!(w);
    let _ = writeln!(w, "The three honesty levels (R4):");
    let _ = writeln!(w);
    let _ = writeln!(w, "| Level | Meaning |");
    let _ = writeln!(w, "| --- | --- |");
    let _ = writeln!(
        w,
        "| `some-true` | A fact reproduced from an authority. **Not established here.** |"
    );
    let _ = writeln!(
        w,
        "| `build` | Constructed here and validated against its oracle. Evidence that the kernels realize the identity, not a proof of it. |"
    );
    let _ = writeln!(w, "| `open` | Measured and reported. **Never asserted.** |");
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "There is no `CN-*` class. Negative testing presupposes inputs the library"
    );
    let _ = writeln!(
        w,
        "rejects, and by C6 there are none beyond non-existence of the requested"
    );
    let _ = writeln!(
        w,
        "object, which `CS-03` covers at view construction. The absence of that"
    );
    let _ = writeln!(
        w,
        "class is itself checked: `cargo xtask audit-limits` fails if any code path"
    );
    let _ = writeln!(w, "returns an error the model does not sanction.");

    for (prefix, title) in CLASSES {
        let rows: Vec<_> = model
            .ids
            .id
            .iter()
            .filter(|r| r.id.starts_with(prefix))
            .collect();
        if rows.is_empty() {
            continue;
        }
        let _ = writeln!(w);
        let _ = writeln!(w, "## `{prefix}*` --- {title}");
        let _ = writeln!(w);
        let _ = writeln!(w, "| ID | Level | Statement | Refuted by |");
        let _ = writeln!(w, "| --- | --- | --- | --- |");
        for r in rows {
            let _ = writeln!(
                w,
                "| `{}` | `{}` | {} | {} |",
                r.id,
                r.level.as_str(),
                cell(&r.statement),
                cell(&r.refuted_by)
            );
        }
    }

    let _ = writeln!(w);
    let _ = writeln!(w, "## Cited authorities");
    let _ = writeln!(w);
    let _ = writeln!(w, "Never re-derived, vendored, or gated on.");
    let _ = writeln!(w);
    let _ = writeln!(w, "| Authority | Citation | Evidence here |");
    let _ = writeln!(w, "| --- | --- | --- |");
    for a in &model.authorities.authority {
        let realized = if a.realized_by.is_empty() {
            "--".to_string()
        } else {
            a.realized_by
                .iter()
                .map(|i| format!("`{i}`"))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let _ = writeln!(w, "| `{}` | {} | {realized} |", a.id, cell(&a.citation));
    }

    let _ = writeln!(w);
    let _ = writeln!(w, "## Claims that are not conformance IDs");
    let _ = writeln!(w);
    let _ = writeln!(w, "| ID | Level | Claim | Refuted by |");
    let _ = writeln!(w, "| --- | --- | --- | --- |");
    for c in &model.ledger.claim {
        let _ = writeln!(
            w,
            "| `{}` | `{}` | {} | {} |",
            c.id,
            c.level.as_str(),
            cell(&c.statement),
            cell(&c.refuted_by)
        );
    }

    if !model.ledger.suspension.is_empty() {
        let _ = writeln!(w);
        let _ = writeln!(w, "## Suspended rules");
        let _ = writeln!(w);
        let _ = writeln!(
            w,
            "A working rule suspended for one named scope. What each suspension admits is"
        );
        let _ = writeln!(
            w,
            "read from `model/ledger.toml` by the gate it exempts, so the exemption is model"
        );
        let _ = writeln!(w, "data and not a constant inside the gate.");
        let _ = writeln!(w);
        let _ = writeln!(w, "| ID | Rule | Scope | Admits | Ends |");
        let _ = writeln!(w, "| --- | --- | --- | --- | --- |");
        for s in &model.ledger.suspension {
            let admits = s
                .admits
                .iter()
                .map(|p| format!("`{p}`"))
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(
                w,
                "| `{}` | {} | {} | {} | {} |",
                s.id,
                s.rule,
                cell(&s.scope),
                admits,
                cell(&s.ends)
            );
        }
    }

    out
}
